---
- name: create ec2 instance
  hosts: local
  gather_facts: false
  connection: local
  roles:
    - ec2

- name: configure ec2 instance
  hosts: ${group_kibana}
  user: ubuntu
  gather_facts: false
  roles:
    - kibana
